### ISSUE TITLE
Animation problems on android prod build

### ISSUE THREAD

**Issue by tristola** [ReactFinland/react-finland-app#47]
The animations on TalkCard and WorkShopCard are not working in android or ios release variant
They work on dev builds

Is probably related to this
https://github.com/oblador/react-native-animatable/issues/89#issuecomment-328757127

**Comment by akx** [comment]
I can repro this issue – animations don't show up on Android in release mode. However release builds don't even have the option to enable/disable remote JS debugging, so the comment linked could be a red herring. When using a debug build and enabling remote JS debugging from the `adb shell input keyevent 82` menu, animations do work.
